### ISSUE TITLE
provisioned concurrency 대신 주기적인 호출 기능 추가

### ISSUE THREAD

**Issue by hyu-leeky** [ddps-lab/profet#1]
eventbridge 를 활용한 1분에 한번씩 호출되게 하기.

**Comment by hyoonseo159357** [comment]
프로비저닝은 삭제하고, Eventbridge 를 통해서 1분에 한번씩 호출되게끔 변경해주었습니다.

**Comment by hyu-leeky** [comment]
빠르다! 이제 close 하자.

**Comment by hyu-leeky** [comment]
1분마다 제대로 실행되는지 확인 필요. 실행해보니 굉장히 오래 걸리는게 제대로 실행이 안될수도 있겠다는 생각이 드네. 람다 로그 파일이나 클라우드 와치 등을 통해서 정상적으로 호출되고 있는지 확인 필요.
