### ISSUE TITLE
실행 샘플 파일을 굳이 업데이트 하지 않아도 데모가 실행되게끔 개선

### ISSUE THREAD

**Issue by hyu-leeky** [ddps-lab/profet#3]
현재 데모 시스템은 반드시 사용자가 샘플 파일을 다운 받은 후 별도로 업로드를 해줘야 하는데,
이게 처음에 시도해보는 사람에게는 귀찮을수 있을것 같아.
파일 첨부 없이 그냥 submit 만 누르면 내장 되어 있는 기본 데이터로 결과물을 보여주게끔 개선 할 필요가 있음.

**Comment by hyu-leeky** [comment]
가능한 방법으로 textbox 를 만들어서 copy-paste 를 통해서 진행이 가능하게끔 해주면 어떨까 싶어. textbox 에는 default 값이 입력되어 있고. textbox 에서 입력이 있을 경우에는 front-end 단에서 파일로 만들어서 api gateway 로 post 해주면 될것 같아.

**Comment by H0zzae** [comment]
input value를 file형식으로 변환하여 전달해야할지, 아니면 text 형태로 전달이 가능한지에 대한 테스트를 시행해 보고 향후 진행 방향을 결정할 예정입니다. (~6/12)

**Comment by H0zzae** [comment]
사용자가 test data를 다운받고 다시 업로드 하는 플로우를 줄이게끔 Test Data A, B 버튼을 클릭시 바로 해당 sampleData 값을 서버에 전달해서 그래프에 띄워지게끔 구현이 되었습니다. 
혹시 샘플 데이터 값이 사용자에게 보여지거나 다운받을 수 있게끔 구현해야 할까요?

**Comment by hyu-leeky** [comment]
지금의 화면에서 Test Data A 를 클릭시에 그냥 요청이 바로 가버린다는 이야기인거죠? 그게 직관적일런지 모르겠네요. 특정 링크를 눌렀을때 실행이 된다면 그런 특성을 설명해줘야 하는데 그런 설명을 추가하는게 쉬울런지는 모르겠네요. 혹시 textbox 를 추가하는건 많이 일이 복잡해질까요?

**Comment by H0zzae** [comment]
Profiling Feature 부분에 파일 업로드가 아닌 text-box으로 변경을 말씀하시는걸까요?
text-box로 변경은 가능하지만, 사용자의 입력이 잘못 됐을 경우의 예외처리하는데 어려움이 있지 않을까 생각됩니다.

**Comment by hyu-leeky** [comment]
파일 업로드와 text-box 를 둘다 가지고 갔으면 해요. 만약에 사용자의 입력이 잘못될 경우의 예외 처리는 text-box 나 file 이나 똑같이 문제가 있지 않을까요? 파일에 이상한 값이 입력되어 있으면 그걸 서버에서 처리할것 같아서요.

**Comment by H0zzae** [comment]
네 그럼 testData 버튼에 따라 text-box의 default값이 변하게끔 하고
file upload가 있을 경우, text-box의 값 대신 File의 값을 서버에게 전송하는 형식으로 수정해 보겠습니다.
이런 형식으로 진행될 것 같습니다. 
<img width="508" alt="image" src="https://user-images.githubusercontent.com/39540561/173301421-f6d3fea6-48ce-439c-a47d-bcae7639161f.png">

**Comment by hyu-leeky** [comment]
아니면 upload 칸을 보이게 하는 것보다는 2가지 옵션을 주고 (파일 업로드, 텍스트박스) 기본을 텍스트 박스로 한 다음에 default 값을 다 채워놓고 그냥 submit 만 누르면 되게끔 하구요. 
만약에 file upload 를 선택하면 텍스트 박스는 없어지거나 보이지 않으면서 파일 업로드 화면을 보이게 하는건 가능할까요?

**Comment by H0zzae** [comment]
네 가능합니다!
그럼 profiling featrue에 Radio button처럼 [File Upload / Text Box(default)] 선택지를 두고, 
사용자의 선택지에 따라 아래 content가 달라지게끔 구현하면 될까요?

**Comment by hyu-leeky** [comment]
네 그렇게 할 수 있으면 좋을것 같아요. 처음 랜딩 화면에서 default 는 textbox 가 좋겠구요 :)

**Comment by H0zzae** [comment]
넵! 알겠습니다! 작업완료되면 다시 코멘트 남기도록 하겠습니다 !

**Comment by H0zzae** [comment]
작업완료하여 #5 풀리퀘 요청드렸습니다.
![image](https://user-images.githubusercontent.com/39540561/174964165-e7a0ac6e-43f7-4407-95b1-178098dda84b.png)

**Comment by james-sungjae-lee** [comment]
Pull Request 의 Merge 를 완료하였고, 해당 페이지는 아래의 링크에서 확인 가능합니다.

https://ddps-lab.github.io/profet/demo/demo.html

현재 profet.ddps.cloud 에는 업데이트 하지 않은 상태입니다. 이 경우에는 S3로 배포되고 있기 때문에 profet 수정사항이 모두 반영되고 한 번에 업데이트 하겠습니다.

**Comment by hyu-leeky** [comment]
오케이. 잘했다. 최초 랜딩 페이지에서 default 값을 추가하는게 좋지 않을까? 위의 Test A 혹은 B 를 누르면 채워지기는 하는데, 아예 default 가 하나 있으면 좋을것 같아. 어떻게 사용되는지 설명도 추가하면 좋을것 같아.

**Comment by james-sungjae-lee** [comment]
네 교수님, demo 페이지를 처음 들어갔을 때 이미 profiling feature 와 anchor latency 가 채워져 있었으면 좋겠다는 말씀이 맞을까요?
구현하는 것은 어렵지 않을 것 같지만, 해당 feature 및 latency 가 어떤 workload(model - bs - ps) 인지 모른다는 단점이 있습니다.
그렇게 구현한다면 default workload의 정보에 대해서 다른 곳에 명시를 해 줄 필요가 있어 보입니다.

사용 방법은 demo 서비스를 사용하는 방법을 말씀하시는 것으로 생각했을 때, documentation 쪽에 추가하는 것이 좋지 않을까 싶습니다.
demo 페이지에 작성하기에는 공간이 많지 않을 것 같아서요. 이 때 default workload 에 대한 정보도 함께 작성이 가능할 것 같습니다.

**Comment by hyu-leeky** [comment]
응 성재야 맞아. 사람들이 이런 시스템을 사용해보면 자세하게 읽어보고 써보는 사람도 있지만 대부분은 최소한의 interaction 으로 동작하는걸 보고 싶어 하거든. 지적한대로 어떤 모델에서 측정된 값인지 알수가 없으니, 해당 워크로드에 대한 정보는 별도로 명시할 필요가 있겠다. 
메인페이지에서 이야기가 되면 좋겠지만 공간이 부족하다면 document 페이지에 추가하고, 메인 페이지에서 document 페이지로 넘어가는 링크를 만들어 주는 것도 좋겠다.

**Comment by james-sungjae-lee** [comment]
네 알겠습니다. 그러면 Test A 데이터를 default 로 생성하는 코드를 @H0zzae 와 함께 작업 진행하겠습니다. 현재 Document 에는 Feature Generation 을 중심으로 설명이 되어 있는데, 이를 두 부분으로 나누어 Demo 사용법에 관해서도 설명을 작성해 보겠습니다.

**Comment by hyu-leeky** [comment]
이건 언제 반영되나요?

**Comment by H0zzae** [comment]
pull request #6 로 현재 testA 데이터를 디폴트 값으로 설정하는 코드를 올려두었습니다.
추후, demo 사용법에 대해 작성된 문서를 전달받으면 document에 추가하고, demo의 input부분에 데모 사용법에 연결되는 링크를 달아 이동 가능하게끔 구현될 예정입니다.

**Comment by hyu-leeky** [comment]
그런데 profet.ddps.cloud 를 방문하면 여전히 이전 페이지 인것 같아요.

**Comment by james-sungjae-lee** [comment]
교수님, 현재 데모 페이지 개발은 ddps-lab/profet 계정에서 진행되고 있습니다.
https://ddps-lab.github.io/profet/demo/demo.html

profet.ddps.cloud 의 경우 제가 S3 에 올려놓은 정적 웹이며, 아직 업데이트 하지 않았습니다.
수정사항의 반영이 모두 완료된 다음 진행하려 생각했는데, 이 정도에서 한 번 업데이트 할까요?

ps. 제가 repository 를 잘못 알고 있어 수정했습니다

**Comment by hyu-leeky** [comment]
응 그러자. 조금 이라도 업데이트 되면 즉각 반영해도 괜찮을것 같아.

**Comment by james-sungjae-lee** [comment]
네 지금까지 업데이트 사항 반영하였고, profet.ddps.cloud 를 통해서 확인 완료했습니다
혹시 업데이트가 안보이시는 경우에는 cache 를 삭제하거나 incognito 모드로 접속해서 확인하시기 바랍니다

**Comment by hyu-leeky** [comment]
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/17699616/176842278-06cb3916-02d7-4757-b550-ddf0ce698c43.png">

음.. 업데이트는 된것 같은데 화면이 이상하네. submit 눌러도 파일을 업로드 하라고 하고.

**Comment by james-sungjae-lee** [comment]
교수님, 저도 예전에 같은 형태로 깨지는 문제가 있었는데, 이전의 cache 와 충돌이 있어서 그랬던 것이었습니다.
혹시 cache 를 지우거나 incognito 모드로 시도해 보실 수 있을까요?

**Comment by hyu-leeky** [comment]
incognito 로 하니 괜찮네. 메뉴의 세부 워딩은 약간 바꿀게 있어보이는데 그건 차차 조금씩 수정해나가고. 이 이슈는 close 해도 되겠다.
