### ISSUE TITLE
profet.ddps.cloud 랜딩 페이지를 데모 페이지로 되게끔 수정

### ISSUE THREAD

**Issue by hyu-leeky** [ddps-lab/profet#4]
현재는 데모 페이지로 이동하려면 탭을 클릭해야 하는데
초기 랜딩 페이지를 데모 페이지로 하는게 더 나아 보임.

**Comment by james-sungjae-lee** [comment]
S3 의 static web hosting 설정을 변경하여 demo.html 이 default page 가 되도록 설정 완료하였습니다

**Comment by hyu-leeky** [comment]
오케이 잘했다. 이걸 가능하면 코드 커밋과 issue 를 연동해서 PR 등을 했으면 좋겠는데. 그건 시간을 두고 진행을 해보자.
